import { Dimensions, StyleSheet } from "react-native";

const CARD_WIDTH = Math.min(Dimensions.get('screen').width * 0.75, 400);

export const styles = StyleSheet.create({
    /** Header */
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderBottomWidth: 1,
      borderColor: '#e3e3e3',
    },
    headerAction: {
      width: 40,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    /** Search */
    search: {
      position: 'relative',
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: 0,
      backgroundColor: '#F0F0F0',
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    searchIcon: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: 34,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2,
    },
    searchControl: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      paddingLeft: 34,
      width: '100%',
      fontSize: 16,
      fontWeight: '500',
    },
    /** Content */
    content: {
      paddingTop: 12,
      paddingHorizontal: 24,
    },
    contentActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 18,
      marginHorizontal: -6,
      marginBottom: 0,
    },
    /** Profile */
    profile: {
      paddingTop: 4,
      paddingBottom: 16,
    },
    profileTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    profileBody: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: 0,
      paddingLeft: 16,
    },
    profileTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      lineHeight: 32,
      color: '#121a26',
      marginBottom: 6,
    },
    profileSubtitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#778599',
    },
    profileDescription: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      color: '#778599',
    },
    profileTags: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    profileTagsItem: {
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 18,
      color: '#266ef1',
      marginRight: 4,
    },
    /** Avatar */
    avatar: {
      position: 'relative',
    },
    avatarImg: {
      width: 80,
      height: 80,
      borderRadius: 9999,
    },
    avatarNotification: {
      position: 'absolute',
      borderRadius: 9999,
      borderWidth: 2,
      borderColor: '#fff',
      bottom: 0,
      right: -2,
      width: 21,
      height: 21,
      backgroundColor: '#22C55E',
    },
    /** Stats */
    stats: {
      backgroundColor: '#fff',
      flexDirection: 'row',
      padding: 20,
      borderRadius: 12,
      shadowColor: '#90a0ca',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 1,
    },
    statsItem: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: 0,
      borderLeftWidth: 1,
      borderColor: 'rgba(189, 189, 189, 0.32)',
    },
    statsItemText: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 18,
      color: '#778599',
      marginBottom: 5,
    },
    statsItemValue: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 20,
      color: '#121a26',
    },
    /** Button */
    btn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderWidth: 2,
      backgroundColor: 'transparent',
      borderColor: '#266EF1',
    },
    btnText: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      color: '#266EF1',
    },
    btnPrimary: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderWidth: 2,
      backgroundColor: '#266EF1',
      borderColor: '#266EF1',
    },
    btnPrimaryText: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      color: '#fff',
    },
    /** List */
    list: {
      marginTop: 16,
    },
    listHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 24,
    },
    listTitle: {
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 22,
      color: '#121a26',
    },
    listAction: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      color: '#778599',
    },
    listContent: {
      paddingVertical: 12,
      paddingHorizontal: 18,
    },
    /** Card */
    card: {
      width: CARD_WIDTH,
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: '#fff',
      marginHorizontal: 6,
      shadowColor: '#90a0ca',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 1,
    },
    cardTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    cardIcon: {
      width: 44,
      height: 44,
      borderRadius: 9999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#eff1f5',
    },
    cardBody: {
      paddingLeft: 12,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: '600',
      lineHeight: 18,
      color: '#121a26',
      marginBottom: 4,
    },
    cardSubtitle: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      color: '#778599',
    },
    cardFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 18,
    },
    cardFooterText: {
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
      color: '#778599',
    },
  });